syntax on
set number

" Tabs and ident
filetype plugin indent on
set smartindent
set shiftwidth=4
set softtabstop=4
set expandtab

" Highlight current line
set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine guibg=#303000 ctermbg=238

" Folding
setlocal foldmethod=syntax
set foldlevelstart=99

