" Plugings:
" sudo apt install vim-python-jedi
" vim-addons install python-jedi
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#popup_on_dot = 0
let g:jedi#show_call_signatures = "1"

" Interface
syntax on
set number

" Tabs and ident
filetype plugin indent on
set smartindent
set shiftwidth=4
set softtabstop=4
set expandtab

" Highlight current line
set cursorline
hi cursorline cterm=none term=none
autocmd WinEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
highlight CursorLine guibg=#303000 ctermbg=238

" Folding
setlocal foldmethod=syntax
set foldlevelstart=99


